# Generated by Django 6.0.5 on 2026-05-26 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_project', '0002_brand_store_supplier_review_order_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, upload_to='categories/', verbose_name='Изображение (фон)'),
        ),
    ]
