# Generated by Django 6.0.5 on 2026-05-26 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_project', '0004_employee_photo_product_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='logo',
            field=models.ImageField(blank=True, upload_to='suppliers/', verbose_name='Логотип'),
        ),
    ]
